const UPDATE_CONTENT = "UPDATE_CONTENT";
const UPDATE_COMMENT = "UPDATE_COMMENT";
const DETAIL_CONTENT = "DETAIL_CONTENT";
const DETAIL_COMMENT = "DETAIL_COMMENT";
const FIRST_CALL = "FIRST_CALL";
export { UPDATE_COMMENT, UPDATE_CONTENT, DETAIL_CONTENT, DETAIL_COMMENT, FIRST_CALL };
